name: logperformance CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: |
          pip install poetry pytest
          pip install -e .
          poetry install
      - run: pytest tests/
  release:
    permissions:
      id-token: write
      contents: read
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: |
          pip install poetry
          poetry build
          poetry publish --username __token__ --password "${{ secrets.PYPI_TOKEN }}"
